server:
  port: 8081
  
spring:

  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservice
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver              //No need to add
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
#    properties:                                              //No need to add, auto detected
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import:
      configserver:http://localhost:8085
      
#  profiles:                                                   #by default it takes default configuration
#    active: dev

#eureka:
#  instance:
#    prefer-ip-address: true                                   #On clicking  DESKTOP-EF2AUJ4:8081 on eureka you get ip instead hostname
#  client:                                                     #No need to add default are true(all below)
#    fetch-registry: true
#    register-with-eureka: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 20
        failureRateThreshold: 50
        minimumNumberOfCalls: 5                         
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 14
        slidingWindowType: COUNT_BASED
        
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
        
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 15s
        limit-for-period: 2
        timeout-duration: 5s                          #after successfull response wait time for bad requests 
