server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservice
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver              //No need to add
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
#    properties:                                              //No need to add, auto detected
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USER-SERVICE

eureka:
  instance:
    prefer-ip-address: true                                   #On clicking  DESKTOP-EF2AUJ4:8081 on eureka you get ip instead hostname
#  client:                                                     #No need to add default are true
#    fetch-registry: true
#    register-with-eureka: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka