server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservice
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver              //No need to add
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
#    properties:                                              //No need to add, auto detected
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect