server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingmicroservice
   
  application:
    name: RATING-SERVICE
      

eureka:
  instance:
    prefer-ip-address: true                                   #On clicking  DESKTOP-EF2AUJ4:8081 on eureka you get ip instead hostname
#  client:                                                     #No need to add default are true
#    fetch-registry: true
#    register-with-eureka: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka